Header      header
uint8       state
string      state_string
uint8       running_state
string      running_state_string
uint8       waiting_state
string      waiting_state_string
float64     speed
float64     heading_rad
float64     heading_deg
uint8       gear
string      gear_string
uint8       direction_mode
string      direction_mode_string
uint8       operation_mode
string      operation_mode_string

