# Header information
Header header

# Valence for fear-emotion concerning roll-overs
float64 fearRollOverValence

# Valence for fear-emotion concerning getting lost
float64 fearGettingLostValence

# Feeling valence for Tilt-over
float64 tiltOverFeeling

# Hormone level for Tilt-over
float64 tiltOverHormone

# Feeling valence for Roll-over
float64 rollOverFeeling

# Hormone level for Roll-over
float64 rollOverHormone

# Feeling valence for gps
float64 gpsFeeling

# Hormone level for gsp
float64 gpsHormone

# Feeling valence for dgps
float64 dgpsFeeling

# Hormone level for dgsp
float64 dgpsHormone

# Feeling valence for compass
float64 compassFeeling

# Hormone level for compass
float64 compassHormone

