Header header

# Accelerationangle in x-direction
float64 angleX

# Accelerationangle in y-direction
float64 angleY

# Accelerationangle in x-direction normalized (0...1) in respect to maximum angles
float64 angleXnorm

# Accelerationangle in y-direction normalized (0...1) in respect to maximum angles
float64 angleYnorm

# Estimated fear value in x-direction (0...1)
float64 sigmaX

# Estimated fear value in y-direction (0...1)
float64 sigmaY

# Length of the acceleration vector
float64 length

# Estimation of the module range 0...1
float64 estimation

# Currently set maximum tilt angle
float64 maxTilt

# Currently set maximum roll angle
float64 maxRoll

# Current speed of vehicle
float64 currentSpeed

