"""autogenerated by genpy from ezls_msgs/BmlCommanderCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BmlCommanderCommand(genpy.Message):
  _md5sum = "05f10de8eb139332ee9e1b902504ab51"
  _type = "ezls_msgs/BmlCommanderCommand"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 timestamp

# BML type
string type

# Offset for UAV1
float64 uav1XOffset
float64 uav1YOffset

# Offset for UAV2
float64 uav2XOffset
float64 uav2YOffset




"""
  __slots__ = ['timestamp','type','uav1XOffset','uav1YOffset','uav2XOffset','uav2YOffset']
  _slot_types = ['float64','string','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,type,uav1XOffset,uav1YOffset,uav2XOffset,uav2YOffset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BmlCommanderCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.type is None:
        self.type = ''
      if self.uav1XOffset is None:
        self.uav1XOffset = 0.
      if self.uav1YOffset is None:
        self.uav1YOffset = 0.
      if self.uav2XOffset is None:
        self.uav2XOffset = 0.
      if self.uav2YOffset is None:
        self.uav2YOffset = 0.
    else:
      self.timestamp = 0.
      self.type = ''
      self.uav1XOffset = 0.
      self.uav1YOffset = 0.
      self.uav2XOffset = 0.
      self.uav2YOffset = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_d.pack(self.timestamp))
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4d.pack(_x.uav1XOffset, _x.uav1YOffset, _x.uav2XOffset, _x.uav2YOffset))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.uav1XOffset, _x.uav1YOffset, _x.uav2XOffset, _x.uav2YOffset,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_d.pack(self.timestamp))
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4d.pack(_x.uav1XOffset, _x.uav1YOffset, _x.uav2XOffset, _x.uav2YOffset))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.uav1XOffset, _x.uav1YOffset, _x.uav2XOffset, _x.uav2YOffset,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4d = struct.Struct("<4d")
_struct_d = struct.Struct("<d")
