"""autogenerated by genpy from ezls_msgs/ContinousPointCloudOutputData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg
import ezls_msgs.msg
import sensor_msgs.msg

class ContinousPointCloudOutputData(genpy.Message):
  _md5sum = "5e6e03276f1b6b18be57c2b9f89c297d"
  _type = "ezls_msgs/ContinousPointCloudOutputData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Point cloud.
sensor_msgs/PointCloud2 pointCloud

# Point cloud parameters.
ezls_msgs/PointCloud3Parameters pointCloudParams

# Texture image.
sensor_msgs/Image texImage

# Texture coordinates
TexCoordsArray texCoords

================================================================================
MSG: sensor_msgs/PointCloud2
# This message holds a collection of N-dimensional points, which may
# contain additional information such as normals, intensity, etc. The
# point data is stored as a binary blob, its layout described by the
# contents of the "fields" array.

# The point cloud data may be organized 2d (image-like) or 1d
# (unordered). Point clouds organized as 2d images may be produced by
# camera depth sensors such as stereo or time-of-flight.

# Time of sensor data acquisition, and the coordinate frame ID (for 3d
# points).
Header header

# 2D structure of the point cloud. If the cloud is unordered, height is
# 1 and width is the length of the point cloud.
uint32 height
uint32 width

# Describes the channels and their layout in the binary data blob.
PointField[] fields

bool    is_bigendian # Is this data bigendian?
uint32  point_step   # Length of a point in bytes
uint32  row_step     # Length of a row in bytes
uint8[] data         # Actual point data, size is (row_step*height)

bool is_dense        # True if there are no invalid points

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: sensor_msgs/PointField
# This message holds the description of one point entry in the
# PointCloud2 message format.
uint8 INT8    = 1
uint8 UINT8   = 2
uint8 INT16   = 3
uint8 UINT16  = 4
uint8 INT32   = 5
uint8 UINT32  = 6
uint8 FLOAT32 = 7
uint8 FLOAT64 = 8

string name      # Name of field
uint32 offset    # Offset from start of point struct
uint8  datatype  # Datatype enumeration, see above
uint32 count     # How many elements in the field

================================================================================
MSG: ezls_msgs/PointCloud3Parameters
#ID of the point cloud
uint32 id

#Number of points in point cloud
uint32 numPoints

#Descriptor if the point cloud
string descriptor

#Absolute Timestamp of begin of point recording
float64 timestampBegin

#Absolute Timestamp of end of point recording
float64 timestampEnd

#Direction of point acquisition
int8 acquisitionDirection

#Global 3D Vehicle state at begin of point recording
Pose3 globalVs3dBegin

#Global 3D Vehicle state at end of point recording
Pose3 globalVs3dEnd

#Global 3D Vehicle state at begin of point recording, relative
Pose3 localVs3dBegin

#Global 3D Vehicle state at end of point recording, relative
Pose3 localVs3dEnd

================================================================================
MSG: ezls_msgs/Pose3
geometry_msgs/Vector3 position
geometry_msgs/Vector3 orientation

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of cameara
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in src/image_encodings.cpp

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: ezls_msgs/TexCoordsArray
Header header
ezls_msgs/Vector2i[] coordinates

================================================================================
MSG: ezls_msgs/Vector2i
int32 x
int32 y

"""
  __slots__ = ['pointCloud','pointCloudParams','texImage','texCoords']
  _slot_types = ['sensor_msgs/PointCloud2','ezls_msgs/PointCloud3Parameters','sensor_msgs/Image','ezls_msgs/TexCoordsArray']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pointCloud,pointCloudParams,texImage,texCoords

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ContinousPointCloudOutputData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pointCloud is None:
        self.pointCloud = sensor_msgs.msg.PointCloud2()
      if self.pointCloudParams is None:
        self.pointCloudParams = ezls_msgs.msg.PointCloud3Parameters()
      if self.texImage is None:
        self.texImage = sensor_msgs.msg.Image()
      if self.texCoords is None:
        self.texCoords = ezls_msgs.msg.TexCoordsArray()
    else:
      self.pointCloud = sensor_msgs.msg.PointCloud2()
      self.pointCloudParams = ezls_msgs.msg.PointCloud3Parameters()
      self.texImage = sensor_msgs.msg.Image()
      self.texCoords = ezls_msgs.msg.TexCoordsArray()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.pointCloud.header.seq, _x.pointCloud.header.stamp.secs, _x.pointCloud.header.stamp.nsecs))
      _x = self.pointCloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.pointCloud.height, _x.pointCloud.width))
      length = len(self.pointCloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.pointCloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_IBI.pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_struct_B2I.pack(_x.pointCloud.is_bigendian, _x.pointCloud.point_step, _x.pointCloud.row_step))
      _x = self.pointCloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B2I.pack(_x.pointCloud.is_dense, _x.pointCloudParams.id, _x.pointCloudParams.numPoints))
      _x = self.pointCloudParams.descriptor
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2db24d3I.pack(_x.pointCloudParams.timestampBegin, _x.pointCloudParams.timestampEnd, _x.pointCloudParams.acquisitionDirection, _x.pointCloudParams.globalVs3dBegin.position.x, _x.pointCloudParams.globalVs3dBegin.position.y, _x.pointCloudParams.globalVs3dBegin.position.z, _x.pointCloudParams.globalVs3dBegin.orientation.x, _x.pointCloudParams.globalVs3dBegin.orientation.y, _x.pointCloudParams.globalVs3dBegin.orientation.z, _x.pointCloudParams.globalVs3dEnd.position.x, _x.pointCloudParams.globalVs3dEnd.position.y, _x.pointCloudParams.globalVs3dEnd.position.z, _x.pointCloudParams.globalVs3dEnd.orientation.x, _x.pointCloudParams.globalVs3dEnd.orientation.y, _x.pointCloudParams.globalVs3dEnd.orientation.z, _x.pointCloudParams.localVs3dBegin.position.x, _x.pointCloudParams.localVs3dBegin.position.y, _x.pointCloudParams.localVs3dBegin.position.z, _x.pointCloudParams.localVs3dBegin.orientation.x, _x.pointCloudParams.localVs3dBegin.orientation.y, _x.pointCloudParams.localVs3dBegin.orientation.z, _x.pointCloudParams.localVs3dEnd.position.x, _x.pointCloudParams.localVs3dEnd.position.y, _x.pointCloudParams.localVs3dEnd.position.z, _x.pointCloudParams.localVs3dEnd.orientation.x, _x.pointCloudParams.localVs3dEnd.orientation.y, _x.pointCloudParams.localVs3dEnd.orientation.z, _x.texImage.header.seq, _x.texImage.header.stamp.secs, _x.texImage.header.stamp.nsecs))
      _x = self.texImage.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.texImage.height, _x.texImage.width))
      _x = self.texImage.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.texImage.is_bigendian, _x.texImage.step))
      _x = self.texImage.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.texCoords.header.seq, _x.texCoords.header.stamp.secs, _x.texCoords.header.stamp.nsecs))
      _x = self.texCoords.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.texCoords.coordinates)
      buff.write(_struct_I.pack(length))
      for val1 in self.texCoords.coordinates:
        _x = val1
        buff.write(_struct_2i.pack(_x.x, _x.y))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pointCloud is None:
        self.pointCloud = sensor_msgs.msg.PointCloud2()
      if self.pointCloudParams is None:
        self.pointCloudParams = ezls_msgs.msg.PointCloud3Parameters()
      if self.texImage is None:
        self.texImage = sensor_msgs.msg.Image()
      if self.texCoords is None:
        self.texCoords = ezls_msgs.msg.TexCoordsArray()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pointCloud.header.seq, _x.pointCloud.header.stamp.secs, _x.pointCloud.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pointCloud.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pointCloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.pointCloud.height, _x.pointCloud.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pointCloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _struct_IBI.unpack(str[start:end])
        self.pointCloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.pointCloud.is_bigendian, _x.pointCloud.point_step, _x.pointCloud.row_step,) = _struct_B2I.unpack(str[start:end])
      self.pointCloud.is_bigendian = bool(self.pointCloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pointCloud.data = str[start:end].decode('utf-8')
      else:
        self.pointCloud.data = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.pointCloud.is_dense, _x.pointCloudParams.id, _x.pointCloudParams.numPoints,) = _struct_B2I.unpack(str[start:end])
      self.pointCloud.is_dense = bool(self.pointCloud.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pointCloudParams.descriptor = str[start:end].decode('utf-8')
      else:
        self.pointCloudParams.descriptor = str[start:end]
      _x = self
      start = end
      end += 221
      (_x.pointCloudParams.timestampBegin, _x.pointCloudParams.timestampEnd, _x.pointCloudParams.acquisitionDirection, _x.pointCloudParams.globalVs3dBegin.position.x, _x.pointCloudParams.globalVs3dBegin.position.y, _x.pointCloudParams.globalVs3dBegin.position.z, _x.pointCloudParams.globalVs3dBegin.orientation.x, _x.pointCloudParams.globalVs3dBegin.orientation.y, _x.pointCloudParams.globalVs3dBegin.orientation.z, _x.pointCloudParams.globalVs3dEnd.position.x, _x.pointCloudParams.globalVs3dEnd.position.y, _x.pointCloudParams.globalVs3dEnd.position.z, _x.pointCloudParams.globalVs3dEnd.orientation.x, _x.pointCloudParams.globalVs3dEnd.orientation.y, _x.pointCloudParams.globalVs3dEnd.orientation.z, _x.pointCloudParams.localVs3dBegin.position.x, _x.pointCloudParams.localVs3dBegin.position.y, _x.pointCloudParams.localVs3dBegin.position.z, _x.pointCloudParams.localVs3dBegin.orientation.x, _x.pointCloudParams.localVs3dBegin.orientation.y, _x.pointCloudParams.localVs3dBegin.orientation.z, _x.pointCloudParams.localVs3dEnd.position.x, _x.pointCloudParams.localVs3dEnd.position.y, _x.pointCloudParams.localVs3dEnd.position.z, _x.pointCloudParams.localVs3dEnd.orientation.x, _x.pointCloudParams.localVs3dEnd.orientation.y, _x.pointCloudParams.localVs3dEnd.orientation.z, _x.texImage.header.seq, _x.texImage.header.stamp.secs, _x.texImage.header.stamp.nsecs,) = _struct_2db24d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.texImage.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.texImage.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.texImage.height, _x.texImage.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.texImage.encoding = str[start:end].decode('utf-8')
      else:
        self.texImage.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.texImage.is_bigendian, _x.texImage.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.texImage.data = str[start:end].decode('utf-8')
      else:
        self.texImage.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.texCoords.header.seq, _x.texCoords.header.stamp.secs, _x.texCoords.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.texCoords.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.texCoords.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.texCoords.coordinates = []
      for i in range(0, length):
        val1 = ezls_msgs.msg.Vector2i()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _struct_2i.unpack(str[start:end])
        self.texCoords.coordinates.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.pointCloud.header.seq, _x.pointCloud.header.stamp.secs, _x.pointCloud.header.stamp.nsecs))
      _x = self.pointCloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.pointCloud.height, _x.pointCloud.width))
      length = len(self.pointCloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.pointCloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_IBI.pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_struct_B2I.pack(_x.pointCloud.is_bigendian, _x.pointCloud.point_step, _x.pointCloud.row_step))
      _x = self.pointCloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B2I.pack(_x.pointCloud.is_dense, _x.pointCloudParams.id, _x.pointCloudParams.numPoints))
      _x = self.pointCloudParams.descriptor
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2db24d3I.pack(_x.pointCloudParams.timestampBegin, _x.pointCloudParams.timestampEnd, _x.pointCloudParams.acquisitionDirection, _x.pointCloudParams.globalVs3dBegin.position.x, _x.pointCloudParams.globalVs3dBegin.position.y, _x.pointCloudParams.globalVs3dBegin.position.z, _x.pointCloudParams.globalVs3dBegin.orientation.x, _x.pointCloudParams.globalVs3dBegin.orientation.y, _x.pointCloudParams.globalVs3dBegin.orientation.z, _x.pointCloudParams.globalVs3dEnd.position.x, _x.pointCloudParams.globalVs3dEnd.position.y, _x.pointCloudParams.globalVs3dEnd.position.z, _x.pointCloudParams.globalVs3dEnd.orientation.x, _x.pointCloudParams.globalVs3dEnd.orientation.y, _x.pointCloudParams.globalVs3dEnd.orientation.z, _x.pointCloudParams.localVs3dBegin.position.x, _x.pointCloudParams.localVs3dBegin.position.y, _x.pointCloudParams.localVs3dBegin.position.z, _x.pointCloudParams.localVs3dBegin.orientation.x, _x.pointCloudParams.localVs3dBegin.orientation.y, _x.pointCloudParams.localVs3dBegin.orientation.z, _x.pointCloudParams.localVs3dEnd.position.x, _x.pointCloudParams.localVs3dEnd.position.y, _x.pointCloudParams.localVs3dEnd.position.z, _x.pointCloudParams.localVs3dEnd.orientation.x, _x.pointCloudParams.localVs3dEnd.orientation.y, _x.pointCloudParams.localVs3dEnd.orientation.z, _x.texImage.header.seq, _x.texImage.header.stamp.secs, _x.texImage.header.stamp.nsecs))
      _x = self.texImage.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.texImage.height, _x.texImage.width))
      _x = self.texImage.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.texImage.is_bigendian, _x.texImage.step))
      _x = self.texImage.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.texCoords.header.seq, _x.texCoords.header.stamp.secs, _x.texCoords.header.stamp.nsecs))
      _x = self.texCoords.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.texCoords.coordinates)
      buff.write(_struct_I.pack(length))
      for val1 in self.texCoords.coordinates:
        _x = val1
        buff.write(_struct_2i.pack(_x.x, _x.y))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pointCloud is None:
        self.pointCloud = sensor_msgs.msg.PointCloud2()
      if self.pointCloudParams is None:
        self.pointCloudParams = ezls_msgs.msg.PointCloud3Parameters()
      if self.texImage is None:
        self.texImage = sensor_msgs.msg.Image()
      if self.texCoords is None:
        self.texCoords = ezls_msgs.msg.TexCoordsArray()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pointCloud.header.seq, _x.pointCloud.header.stamp.secs, _x.pointCloud.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pointCloud.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pointCloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.pointCloud.height, _x.pointCloud.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pointCloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _struct_IBI.unpack(str[start:end])
        self.pointCloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.pointCloud.is_bigendian, _x.pointCloud.point_step, _x.pointCloud.row_step,) = _struct_B2I.unpack(str[start:end])
      self.pointCloud.is_bigendian = bool(self.pointCloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pointCloud.data = str[start:end].decode('utf-8')
      else:
        self.pointCloud.data = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.pointCloud.is_dense, _x.pointCloudParams.id, _x.pointCloudParams.numPoints,) = _struct_B2I.unpack(str[start:end])
      self.pointCloud.is_dense = bool(self.pointCloud.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pointCloudParams.descriptor = str[start:end].decode('utf-8')
      else:
        self.pointCloudParams.descriptor = str[start:end]
      _x = self
      start = end
      end += 221
      (_x.pointCloudParams.timestampBegin, _x.pointCloudParams.timestampEnd, _x.pointCloudParams.acquisitionDirection, _x.pointCloudParams.globalVs3dBegin.position.x, _x.pointCloudParams.globalVs3dBegin.position.y, _x.pointCloudParams.globalVs3dBegin.position.z, _x.pointCloudParams.globalVs3dBegin.orientation.x, _x.pointCloudParams.globalVs3dBegin.orientation.y, _x.pointCloudParams.globalVs3dBegin.orientation.z, _x.pointCloudParams.globalVs3dEnd.position.x, _x.pointCloudParams.globalVs3dEnd.position.y, _x.pointCloudParams.globalVs3dEnd.position.z, _x.pointCloudParams.globalVs3dEnd.orientation.x, _x.pointCloudParams.globalVs3dEnd.orientation.y, _x.pointCloudParams.globalVs3dEnd.orientation.z, _x.pointCloudParams.localVs3dBegin.position.x, _x.pointCloudParams.localVs3dBegin.position.y, _x.pointCloudParams.localVs3dBegin.position.z, _x.pointCloudParams.localVs3dBegin.orientation.x, _x.pointCloudParams.localVs3dBegin.orientation.y, _x.pointCloudParams.localVs3dBegin.orientation.z, _x.pointCloudParams.localVs3dEnd.position.x, _x.pointCloudParams.localVs3dEnd.position.y, _x.pointCloudParams.localVs3dEnd.position.z, _x.pointCloudParams.localVs3dEnd.orientation.x, _x.pointCloudParams.localVs3dEnd.orientation.y, _x.pointCloudParams.localVs3dEnd.orientation.z, _x.texImage.header.seq, _x.texImage.header.stamp.secs, _x.texImage.header.stamp.nsecs,) = _struct_2db24d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.texImage.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.texImage.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.texImage.height, _x.texImage.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.texImage.encoding = str[start:end].decode('utf-8')
      else:
        self.texImage.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.texImage.is_bigendian, _x.texImage.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.texImage.data = str[start:end].decode('utf-8')
      else:
        self.texImage.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.texCoords.header.seq, _x.texCoords.header.stamp.secs, _x.texCoords.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.texCoords.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.texCoords.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.texCoords.coordinates = []
      for i in range(0, length):
        val1 = ezls_msgs.msg.Vector2i()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _struct_2i.unpack(str[start:end])
        self.texCoords.coordinates.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_IBI = struct.Struct("<IBI")
_struct_BI = struct.Struct("<BI")
_struct_2i = struct.Struct("<2i")
_struct_3I = struct.Struct("<3I")
_struct_B2I = struct.Struct("<B2I")
_struct_2db24d3I = struct.Struct("<2db24d3I")
_struct_2I = struct.Struct("<2I")
