"""autogenerated by genpy from ezls_msgs/PoseObserverOutputData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class PoseObserverOutputData(genpy.Message):
  _md5sum = "8655722e11add1edc9ecf3b15691b34c"
  _type = "ezls_msgs/PoseObserverOutputData"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

# Accelerationangle in x-direction
float64 angleX

# Accelerationangle in y-direction
float64 angleY

# Accelerationangle in x-direction normalized (0...1) in respect to maximum angles
float64 angleXnorm

# Accelerationangle in y-direction normalized (0...1) in respect to maximum angles
float64 angleYnorm

# Estimated fear value in x-direction (0...1)
float64 sigmaX

# Estimated fear value in y-direction (0...1)
float64 sigmaY

# Length of the acceleration vector
float64 length

# Estimation of the module range 0...1
float64 estimation

# Currently set maximum tilt angle
float64 maxTilt

# Currently set maximum roll angle
float64 maxRoll

# Current speed of vehicle
float64 currentSpeed


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','angleX','angleY','angleXnorm','angleYnorm','sigmaX','sigmaY','length','estimation','maxTilt','maxRoll','currentSpeed']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,angleX,angleY,angleXnorm,angleYnorm,sigmaX,sigmaY,length,estimation,maxTilt,maxRoll,currentSpeed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PoseObserverOutputData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.angleX is None:
        self.angleX = 0.
      if self.angleY is None:
        self.angleY = 0.
      if self.angleXnorm is None:
        self.angleXnorm = 0.
      if self.angleYnorm is None:
        self.angleYnorm = 0.
      if self.sigmaX is None:
        self.sigmaX = 0.
      if self.sigmaY is None:
        self.sigmaY = 0.
      if self.length is None:
        self.length = 0.
      if self.estimation is None:
        self.estimation = 0.
      if self.maxTilt is None:
        self.maxTilt = 0.
      if self.maxRoll is None:
        self.maxRoll = 0.
      if self.currentSpeed is None:
        self.currentSpeed = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.angleX = 0.
      self.angleY = 0.
      self.angleXnorm = 0.
      self.angleYnorm = 0.
      self.sigmaX = 0.
      self.sigmaY = 0.
      self.length = 0.
      self.estimation = 0.
      self.maxTilt = 0.
      self.maxRoll = 0.
      self.currentSpeed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_11d.pack(_x.angleX, _x.angleY, _x.angleXnorm, _x.angleYnorm, _x.sigmaX, _x.sigmaY, _x.length, _x.estimation, _x.maxTilt, _x.maxRoll, _x.currentSpeed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.angleX, _x.angleY, _x.angleXnorm, _x.angleYnorm, _x.sigmaX, _x.sigmaY, _x.length, _x.estimation, _x.maxTilt, _x.maxRoll, _x.currentSpeed,) = _struct_11d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_11d.pack(_x.angleX, _x.angleY, _x.angleXnorm, _x.angleYnorm, _x.sigmaX, _x.sigmaY, _x.length, _x.estimation, _x.maxTilt, _x.maxRoll, _x.currentSpeed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.angleX, _x.angleY, _x.angleXnorm, _x.angleYnorm, _x.sigmaX, _x.sigmaY, _x.length, _x.estimation, _x.maxTilt, _x.maxRoll, _x.currentSpeed,) = _struct_11d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_11d = struct.Struct("<11d")
_struct_3I = struct.Struct("<3I")
