"""autogenerated by genpy from ezls_msgs/PoseObserverCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PoseObserverCommand(genpy.Message):
  _md5sum = "d720cdce610d2da276999c742ac0a704"
  _type = "ezls_msgs/PoseObserverCommand"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 timestamp
int32 command

float32 maxRoll
float32 maxTilt

"""
  __slots__ = ['timestamp','command','maxRoll','maxTilt']
  _slot_types = ['float64','int32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,command,maxRoll,maxTilt

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PoseObserverCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.command is None:
        self.command = 0
      if self.maxRoll is None:
        self.maxRoll = 0.
      if self.maxTilt is None:
        self.maxTilt = 0.
    else:
      self.timestamp = 0.
      self.command = 0
      self.maxRoll = 0.
      self.maxTilt = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_di2f.pack(_x.timestamp, _x.command, _x.maxRoll, _x.maxTilt))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.timestamp, _x.command, _x.maxRoll, _x.maxTilt,) = _struct_di2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_di2f.pack(_x.timestamp, _x.command, _x.maxRoll, _x.maxTilt))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.timestamp, _x.command, _x.maxRoll, _x.maxTilt,) = _struct_di2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_di2f = struct.Struct("<di2f")
