"""autogenerated by genpy from ezls_msgs/VsalDGPS.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VsalDGPS(genpy.Message):
  _md5sum = "ed8c0795215ae243807a5262b559b207"
  _type = "ezls_msgs/VsalDGPS"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8   state
float64 uptime
float64 psatHeading
float64 psatPitch
uint8  psatType
float64 utc
float64 latitude
uint8   latitudeDir
float64 longitude
uint8   longitudeDir
uint8   gpsQuality
uint8   numberOfSatellites
uint16  hdop
float64 antennaAltitudeAboveSeaLevel
float64 trackDegreesTrue
float64 trackDegreesMagnetic
float64 kmPerHour
float64 rateOfTurn
uint32  lastValidSignal
uint8   importentValuesValid

"""
  __slots__ = ['state','uptime','psatHeading','psatPitch','psatType','utc','latitude','latitudeDir','longitude','longitudeDir','gpsQuality','numberOfSatellites','hdop','antennaAltitudeAboveSeaLevel','trackDegreesTrue','trackDegreesMagnetic','kmPerHour','rateOfTurn','lastValidSignal','importentValuesValid']
  _slot_types = ['uint8','float64','float64','float64','uint8','float64','float64','uint8','float64','uint8','uint8','uint8','uint16','float64','float64','float64','float64','float64','uint32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state,uptime,psatHeading,psatPitch,psatType,utc,latitude,latitudeDir,longitude,longitudeDir,gpsQuality,numberOfSatellites,hdop,antennaAltitudeAboveSeaLevel,trackDegreesTrue,trackDegreesMagnetic,kmPerHour,rateOfTurn,lastValidSignal,importentValuesValid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VsalDGPS, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = 0
      if self.uptime is None:
        self.uptime = 0.
      if self.psatHeading is None:
        self.psatHeading = 0.
      if self.psatPitch is None:
        self.psatPitch = 0.
      if self.psatType is None:
        self.psatType = 0
      if self.utc is None:
        self.utc = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.latitudeDir is None:
        self.latitudeDir = 0
      if self.longitude is None:
        self.longitude = 0.
      if self.longitudeDir is None:
        self.longitudeDir = 0
      if self.gpsQuality is None:
        self.gpsQuality = 0
      if self.numberOfSatellites is None:
        self.numberOfSatellites = 0
      if self.hdop is None:
        self.hdop = 0
      if self.antennaAltitudeAboveSeaLevel is None:
        self.antennaAltitudeAboveSeaLevel = 0.
      if self.trackDegreesTrue is None:
        self.trackDegreesTrue = 0.
      if self.trackDegreesMagnetic is None:
        self.trackDegreesMagnetic = 0.
      if self.kmPerHour is None:
        self.kmPerHour = 0.
      if self.rateOfTurn is None:
        self.rateOfTurn = 0.
      if self.lastValidSignal is None:
        self.lastValidSignal = 0
      if self.importentValuesValid is None:
        self.importentValuesValid = 0
    else:
      self.state = 0
      self.uptime = 0.
      self.psatHeading = 0.
      self.psatPitch = 0.
      self.psatType = 0
      self.utc = 0.
      self.latitude = 0.
      self.latitudeDir = 0
      self.longitude = 0.
      self.longitudeDir = 0
      self.gpsQuality = 0
      self.numberOfSatellites = 0
      self.hdop = 0
      self.antennaAltitudeAboveSeaLevel = 0.
      self.trackDegreesTrue = 0.
      self.trackDegreesMagnetic = 0.
      self.kmPerHour = 0.
      self.rateOfTurn = 0.
      self.lastValidSignal = 0
      self.importentValuesValid = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B3dB2dBd3BH5dIB.pack(_x.state, _x.uptime, _x.psatHeading, _x.psatPitch, _x.psatType, _x.utc, _x.latitude, _x.latitudeDir, _x.longitude, _x.longitudeDir, _x.gpsQuality, _x.numberOfSatellites, _x.hdop, _x.antennaAltitudeAboveSeaLevel, _x.trackDegreesTrue, _x.trackDegreesMagnetic, _x.kmPerHour, _x.rateOfTurn, _x.lastValidSignal, _x.importentValuesValid))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 101
      (_x.state, _x.uptime, _x.psatHeading, _x.psatPitch, _x.psatType, _x.utc, _x.latitude, _x.latitudeDir, _x.longitude, _x.longitudeDir, _x.gpsQuality, _x.numberOfSatellites, _x.hdop, _x.antennaAltitudeAboveSeaLevel, _x.trackDegreesTrue, _x.trackDegreesMagnetic, _x.kmPerHour, _x.rateOfTurn, _x.lastValidSignal, _x.importentValuesValid,) = _struct_B3dB2dBd3BH5dIB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B3dB2dBd3BH5dIB.pack(_x.state, _x.uptime, _x.psatHeading, _x.psatPitch, _x.psatType, _x.utc, _x.latitude, _x.latitudeDir, _x.longitude, _x.longitudeDir, _x.gpsQuality, _x.numberOfSatellites, _x.hdop, _x.antennaAltitudeAboveSeaLevel, _x.trackDegreesTrue, _x.trackDegreesMagnetic, _x.kmPerHour, _x.rateOfTurn, _x.lastValidSignal, _x.importentValuesValid))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 101
      (_x.state, _x.uptime, _x.psatHeading, _x.psatPitch, _x.psatType, _x.utc, _x.latitude, _x.latitudeDir, _x.longitude, _x.longitudeDir, _x.gpsQuality, _x.numberOfSatellites, _x.hdop, _x.antennaAltitudeAboveSeaLevel, _x.trackDegreesTrue, _x.trackDegreesMagnetic, _x.kmPerHour, _x.rateOfTurn, _x.lastValidSignal, _x.importentValuesValid,) = _struct_B3dB2dBd3BH5dIB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B3dB2dBd3BH5dIB = struct.Struct("<B3dB2dBd3BH5dIB")
